/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * dialogEntrada.java
 *
 * Created on 07/06/2010, 04:40:35
 */

package frontEnd;
import javax.swing.JOptionPane;
import java.sql.*;
import Banco.*;
/**
 *
 * @author Hugo
 */
public class dialogEntrada extends javax.swing.JDialog {
    Conexao con = new Conexao();
    private Statement meustate;
    /** Creates new form dialogEntrada */
    public dialogEntrada(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txtOrigemEntrada = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setText("Inserir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(230, 100, 90, 40);
        getContentPane().add(txtOrigemEntrada);
        txtOrigemEntrada.setBounds(10, 50, 310, 40);

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18));
        jLabel2.setText("Origem:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 10, 130, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try{
                con.Conecta();
                meustate = Conexao.con.createStatement();
                meustate.executeUpdate("INSERT INTO tbl_origem_entrada (descricao_entrada) VALUES ('"+txtOrigemEntrada.getText().toString()+"')");
                JOptionPane.showMessageDialog(null,"Cadastro efetuado com sucesso.");
                con.Fecha();
                txtOrigemEntrada.setText("");
             }
	catch(SQLException erro){
		System.out.println("Não foi possível efetuar o cadastro de origem de entrada.");
                erro.printStackTrace();
                      }// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
   // public static void main(String args[]) {
        //java.awt.EventQueue.invokeLater(new Runnable() {
           public void run() {
                dialogEntrada dialog = new dialogEntrada(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
      //  });
   // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtOrigemEntrada;
    // End of variables declaration//GEN-END:variables

}
