/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frameRelatorioFuncionario.java
 *
 * Created on 04/06/2010, 15:21:11
 */

package frontEnd;

/**
 *
 * @author Andre
 */
public class frameRelatorioFuncionario extends javax.swing.JInternalFrame {

    /** Creates new form frameRelatorioFuncionario */
    public frameRelatorioFuncionario() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblRg = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblBairro = new javax.swing.JLabel();
        lblCep = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        txtBairro = new javax.swing.JTextField();
        txtCEP = new javax.swing.JTextField();
        txtCidade = new javax.swing.JTextField();
        chkAdministrador = new javax.swing.JCheckBox();
        txtCPF = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtRG = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNasc = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        txtNasc1 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        txtNasc2 = new com.toedter.calendar.JDateChooser();
        cmbEstado = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        txtCad1 = new com.toedter.calendar.JDateChooser();
        jLabel12 = new javax.swing.JLabel();
        txtCad2 = new com.toedter.calendar.JDateChooser();
        txtCad = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        cmbFuncionario = new javax.swing.JComboBox();

        setTitle("Relatório de Funcionários");
        getContentPane().setLayout(null);

        lblNome.setFont(new java.awt.Font("sansserif", 1, 12));
        lblNome.setText("Nome:");
        getContentPane().add(lblNome);
        lblNome.setBounds(10, 20, 60, 16);

        lblRg.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblRg.setText("RG:");
        getContentPane().add(lblRg);
        lblRg.setBounds(10, 50, 50, 16);

        lblCpf.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblCpf.setText("CPF:");
        getContentPane().add(lblCpf);
        lblCpf.setBounds(240, 50, 50, 16);

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel8.setText("Dt. nascimento:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 80, 100, 16);

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel7.setText("E-mail:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(430, 50, 40, 16);

        lblBairro.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblBairro.setText("Bairro:");
        getContentPane().add(lblBairro);
        lblBairro.setBounds(220, 110, 38, 16);

        lblCep.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblCep.setText("CEP:");
        getContentPane().add(lblCep);
        lblCep.setBounds(390, 110, 26, 16);

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel6.setText("Cidade: ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 110, 50, 16);

        lblEstado.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        lblEstado.setText("UF:");
        getContentPane().add(lblEstado);
        lblEstado.setBounds(510, 110, 30, 16);
        getContentPane().add(txtBairro);
        txtBairro.setBounds(260, 100, 120, 28);
        getContentPane().add(txtCEP);
        txtCEP.setBounds(420, 100, 80, 28);
        getContentPane().add(txtCidade);
        txtCidade.setBounds(60, 100, 150, 28);

        chkAdministrador.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        chkAdministrador.setText("Admin");
        getContentPane().add(chkAdministrador);
        chkAdministrador.setBounds(490, 10, 70, 30);
        getContentPane().add(txtCPF);
        txtCPF.setBounds(280, 40, 140, 28);
        getContentPane().add(txtNome);
        txtNome.setBounds(50, 10, 230, 28);
        getContentPane().add(txtRG);
        txtRG.setBounds(50, 40, 160, 28);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(480, 40, 230, 28);
        getContentPane().add(txtNasc);
        txtNasc.setBounds(110, 70, 130, 26);

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel9.setText("Nascidos entre:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(250, 70, 90, 30);
        getContentPane().add(txtNasc1);
        txtNasc1.setBounds(350, 70, 130, 26);

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 12));
        jLabel10.setText("e");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(490, 70, 20, 30);
        getContentPane().add(txtNasc2);
        txtNasc2.setBounds(510, 70, 130, 26);

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        getContentPane().add(cmbEstado);
        cmbEstado.setBounds(540, 100, 60, 26);

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel11.setText("Cadastrados entre:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(210, 140, 110, 30);
        getContentPane().add(txtCad1);
        txtCad1.setBounds(320, 140, 130, 26);

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel12.setText("e");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(460, 150, 20, 16);
        getContentPane().add(txtCad2);
        txtCad2.setBounds(480, 140, 130, 26);
        getContentPane().add(txtCad);
        txtCad.setBounds(80, 140, 130, 26);

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel13.setText("Dt. Cadastro:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 140, 90, 20);

        cmbFuncionario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbFuncionario);
        cmbFuncionario.setBounds(290, 10, 190, 26);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkAdministrador;
    private javax.swing.JComboBox cmbEstado;
    private javax.swing.JComboBox cmbFuncionario;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblBairro;
    private javax.swing.JLabel lblCep;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblRg;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtCEP;
    private javax.swing.JTextField txtCPF;
    private com.toedter.calendar.JDateChooser txtCad;
    private com.toedter.calendar.JDateChooser txtCad1;
    private com.toedter.calendar.JDateChooser txtCad2;
    private javax.swing.JTextField txtCidade;
    private javax.swing.JTextField txtEmail;
    private com.toedter.calendar.JDateChooser txtNasc;
    private com.toedter.calendar.JDateChooser txtNasc1;
    private com.toedter.calendar.JDateChooser txtNasc2;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRG;
    // End of variables declaration//GEN-END:variables

}
