/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frameRelatorioServicos.java
 *
 * Created on 04/06/2010, 15:16:57
 */

package frontEnd;

/**
 *
 * @author Andre
 */
public class frameRelatorioServicos extends javax.swing.JInternalFrame {

    /** Creates new form frameRelatorioServicos */
    public frameRelatorioServicos() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        txtCompra = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtCompra2 = new javax.swing.JTextField();
        txtCompra1 = new javax.swing.JTextField();

        setTitle("Relatório de Serviços");
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("sansserif", 1, 12));
        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 40, 16);

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 12));
        jLabel3.setText("Prazo :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 65, 40, 16);

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 12));
        jLabel4.setText("Garantia:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 95, 60, 16);
        getContentPane().add(txtDescricao);
        txtDescricao.setBounds(80, 30, 530, 28);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(50, 60, 70, 28);

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 12));
        jLabel5.setText("Andamento:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(370, 65, 70, 16);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(210, 60, 70, 28);

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 12));
        jLabel6.setText("e");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(280, 65, 10, 16);

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 12));
        jLabel2.setText("Descrição:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 35, 70, 16);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(450, 60, 160, 26);
        getContentPane().add(jTextField4);
        jTextField4.setBounds(70, 90, 70, 28);

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 12));
        jLabel7.setText("Garantia entre:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(160, 95, 90, 16);
        getContentPane().add(jTextField5);
        jTextField5.setBounds(250, 90, 70, 28);

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 12));
        jLabel8.setText("e");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(320, 95, 10, 16);
        getContentPane().add(jTextField6);
        jTextField6.setBounds(330, 90, 70, 28);

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 12));
        jLabel9.setText("Prazo entre:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(140, 65, 70, 16);
        getContentPane().add(jTextField7);
        jTextField7.setBounds(290, 60, 70, 28);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(jComboBox2);
        jComboBox2.setBounds(50, 5, 560, 26);

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel13.setText("Valor entre:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(190, 125, 70, 16);
        getContentPane().add(txtCompra);
        txtCompra.setBounds(80, 120, 90, 28);

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel11.setText("Valor exato:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 125, 70, 16);

        jLabel14.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel14.setText("e");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(345, 125, 7, 16);
        getContentPane().add(txtCompra2);
        txtCompra2.setBounds(360, 120, 80, 28);
        getContentPane().add(txtCompra1);
        txtCompra1.setBounds(260, 120, 80, 28);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField txtCompra;
    private javax.swing.JTextField txtCompra1;
    private javax.swing.JTextField txtCompra2;
    private javax.swing.JTextField txtDescricao;
    // End of variables declaration//GEN-END:variables

}
