/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frameRelatorioCompras.java
 *
 * Created on 04/06/2010, 15:20:33
 */

package frontEnd;

/**
 *
 * @author Andre
 */
public class frameRelatorioCompras extends javax.swing.JInternalFrame {

    /** Creates new form frameRelatorioCompras */
    public frameRelatorioCompras() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtPesqNome = new javax.swing.JTextField();
        cmbCliente = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtPesqNome1 = new javax.swing.JTextField();
        cmbCliente1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtPesqNome2 = new javax.swing.JTextField();
        txtPesqNome3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPesqNome4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNasc1 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        txtNasc2 = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        txtNasc3 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        cmbCliente2 = new javax.swing.JComboBox();

        setTitle("Relatório de Compras");
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel3.setText("Fornecedor:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 0, 70, 20);

        txtPesqNome.setPreferredSize(null);
        getContentPane().add(txtPesqNome);
        txtPesqNome.setBounds(80, 0, 300, 28);

        cmbCliente.setPreferredSize(null);
        cmbCliente.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbClientePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClienteActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCliente);
        cmbCliente.setBounds(390, 0, 360, 26);

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel4.setText("Funcionário:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 30, 80, 20);

        txtPesqNome1.setPreferredSize(null);
        getContentPane().add(txtPesqNome1);
        txtPesqNome1.setBounds(80, 30, 300, 28);

        cmbCliente1.setPreferredSize(null);
        cmbCliente1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbCliente1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmbCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCliente1ActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCliente1);
        cmbCliente1.setBounds(390, 30, 360, 26);

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel5.setText("Valor exato:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 60, 80, 20);

        txtPesqNome2.setPreferredSize(null);
        getContentPane().add(txtPesqNome2);
        txtPesqNome2.setBounds(80, 60, 90, 28);

        txtPesqNome3.setPreferredSize(null);
        getContentPane().add(txtPesqNome3);
        txtPesqNome3.setBounds(260, 60, 80, 28);

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel6.setText("Valor entre:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(190, 60, 70, 20);

        txtPesqNome4.setPreferredSize(null);
        getContentPane().add(txtPesqNome4);
        txtPesqNome4.setBounds(360, 60, 80, 28);

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel7.setText("e");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(350, 60, 10, 20);

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 12));
        jLabel9.setText("Comprados entre:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 100, 110, 16);
        getContentPane().add(txtNasc1);
        txtNasc1.setBounds(120, 90, 200, 26);

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 12));
        jLabel10.setText("e");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(330, 100, 20, 16);
        getContentPane().add(txtNasc2);
        txtNasc2.setBounds(340, 90, 200, 26);

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel11.setText("Comprado em:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(460, 65, 90, 16);
        getContentPane().add(txtNasc3);
        txtNasc3.setBounds(550, 60, 200, 26);

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel8.setText("Tipo de pagamento:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 120, 120, 20);

        cmbCliente2.setPreferredSize(null);
        cmbCliente2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbCliente2PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmbCliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCliente2ActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCliente2);
        cmbCliente2.setBounds(130, 120, 180, 26);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbClientePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbClientePopupMenuWillBecomeInvisible

}//GEN-LAST:event_cmbClientePopupMenuWillBecomeInvisible

    private void cmbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClienteActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cmbClienteActionPerformed

    private void cmbCliente1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbCliente1PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
}//GEN-LAST:event_cmbCliente1PopupMenuWillBecomeInvisible

    private void cmbCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCliente1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cmbCliente1ActionPerformed

    private void cmbCliente2PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbCliente2PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
}//GEN-LAST:event_cmbCliente2PopupMenuWillBecomeInvisible

    private void cmbCliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCliente2ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cmbCliente2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbCliente;
    private javax.swing.JComboBox cmbCliente1;
    private javax.swing.JComboBox cmbCliente2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JDateChooser txtNasc1;
    private com.toedter.calendar.JDateChooser txtNasc2;
    private com.toedter.calendar.JDateChooser txtNasc3;
    private javax.swing.JTextField txtPesqNome;
    private javax.swing.JTextField txtPesqNome1;
    private javax.swing.JTextField txtPesqNome2;
    private javax.swing.JTextField txtPesqNome3;
    private javax.swing.JTextField txtPesqNome4;
    // End of variables declaration//GEN-END:variables

}
