/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frameRelatorioVendas.java
 *
 * Created on 04/06/2010, 15:19:59
 */

package frontEnd;

/**
 *
 * @author Andre
 */
public class frameRelatorioVendas extends javax.swing.JInternalFrame {

    /** Creates new form frameRelatorioVendas */
    public frameRelatorioVendas() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtPesqNome = new javax.swing.JTextField();
        cmbCliente = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtPesqNome1 = new javax.swing.JTextField();
        cmbCliente1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtPesqNome2 = new javax.swing.JTextField();
        txtPesqNome3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPesqNome4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtNasc1 = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        txtNasc2 = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        txtNasc3 = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        cmbCliente2 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        cmbCliente3 = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        cmbCliente4 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        cmbCliente5 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        cmbCliente6 = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        cmbCliente7 = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        cmbCliente8 = new javax.swing.JComboBox();

        setTitle("Relatório de Vendas");
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel3.setText("Cliente:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 0, 50, 20);

        txtPesqNome.setPreferredSize(null);
        getContentPane().add(txtPesqNome);
        txtPesqNome.setBounds(60, 0, 320, 28);

        cmbCliente.setPreferredSize(null);
        cmbCliente.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbClientePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClienteActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCliente);
        cmbCliente.setBounds(390, 0, 360, 26);

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel4.setText("Funcionário:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 30, 80, 20);

        txtPesqNome1.setPreferredSize(null);
        getContentPane().add(txtPesqNome1);
        txtPesqNome1.setBounds(80, 30, 300, 28);

        cmbCliente1.setPreferredSize(null);
        cmbCliente1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbCliente1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmbCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCliente1ActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCliente1);
        cmbCliente1.setBounds(390, 30, 360, 26);

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel5.setText("Valor exato:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 60, 80, 20);

        txtPesqNome2.setPreferredSize(null);
        getContentPane().add(txtPesqNome2);
        txtPesqNome2.setBounds(80, 60, 90, 28);

        txtPesqNome3.setPreferredSize(null);
        getContentPane().add(txtPesqNome3);
        txtPesqNome3.setBounds(260, 60, 80, 28);

        jLabel6.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel6.setText("Valor entre:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(190, 60, 70, 20);

        txtPesqNome4.setPreferredSize(null);
        getContentPane().add(txtPesqNome4);
        txtPesqNome4.setBounds(360, 60, 80, 28);

        jLabel7.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel7.setText("e");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(350, 60, 10, 20);

        jLabel9.setFont(new java.awt.Font("sansserif", 1, 12));
        jLabel9.setText("Vendidos entre:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 100, 90, 16);
        getContentPane().add(txtNasc1);
        txtNasc1.setBounds(100, 90, 200, 26);

        jLabel10.setFont(new java.awt.Font("sansserif", 1, 12));
        jLabel10.setText("e");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(310, 100, 20, 16);
        getContentPane().add(txtNasc2);
        txtNasc2.setBounds(320, 90, 200, 26);

        jLabel11.setFont(new java.awt.Font("sansserif", 1, 12));
        jLabel11.setText("Vendido em:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(460, 60, 80, 16);
        getContentPane().add(txtNasc3);
        txtNasc3.setBounds(530, 60, 200, 26);

        jLabel8.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel8.setText("Tipo de pagamento:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 120, 120, 20);

        cmbCliente2.setPreferredSize(null);
        cmbCliente2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbCliente2PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmbCliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCliente2ActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCliente2);
        cmbCliente2.setBounds(130, 120, 180, 26);

        jLabel12.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel12.setText("Parcelas:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(330, 120, 60, 20);

        cmbCliente3.setPreferredSize(null);
        cmbCliente3.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbCliente3PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmbCliente3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCliente3ActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCliente3);
        cmbCliente3.setBounds(390, 120, 60, 26);

        jLabel13.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel13.setText("Parcelas entre:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(460, 120, 90, 20);

        cmbCliente4.setPreferredSize(null);
        cmbCliente4.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbCliente4PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmbCliente4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCliente4ActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCliente4);
        cmbCliente4.setBounds(550, 120, 60, 26);

        jLabel14.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel14.setText("e");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(620, 120, 10, 20);

        cmbCliente5.setPreferredSize(null);
        cmbCliente5.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbCliente5PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmbCliente5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCliente5ActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCliente5);
        cmbCliente5.setBounds(630, 120, 60, 26);

        jLabel15.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel15.setText("Parcelas pagas:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(10, 150, 100, 20);

        cmbCliente6.setPreferredSize(null);
        cmbCliente6.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbCliente6PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmbCliente6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCliente6ActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCliente6);
        cmbCliente6.setBounds(110, 150, 60, 26);

        jLabel16.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel16.setText("Parcelas pagas entre:");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(180, 150, 140, 20);

        cmbCliente7.setPreferredSize(null);
        cmbCliente7.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbCliente7PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmbCliente7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCliente7ActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCliente7);
        cmbCliente7.setBounds(310, 150, 60, 26);

        jLabel17.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        jLabel17.setText("e");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(380, 150, 10, 20);

        cmbCliente8.setPreferredSize(null);
        cmbCliente8.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                cmbCliente8PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        cmbCliente8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCliente8ActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCliente8);
        cmbCliente8.setBounds(400, 150, 60, 26);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbClientePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbClientePopupMenuWillBecomeInvisible

}//GEN-LAST:event_cmbClientePopupMenuWillBecomeInvisible

    private void cmbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClienteActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cmbClienteActionPerformed

    private void cmbCliente1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbCliente1PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCliente1PopupMenuWillBecomeInvisible

    private void cmbCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCliente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCliente1ActionPerformed

    private void cmbCliente2PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbCliente2PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCliente2PopupMenuWillBecomeInvisible

    private void cmbCliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCliente2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCliente2ActionPerformed

    private void cmbCliente3PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbCliente3PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCliente3PopupMenuWillBecomeInvisible

    private void cmbCliente3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCliente3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCliente3ActionPerformed

    private void cmbCliente4PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbCliente4PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCliente4PopupMenuWillBecomeInvisible

    private void cmbCliente4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCliente4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCliente4ActionPerformed

    private void cmbCliente5PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbCliente5PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCliente5PopupMenuWillBecomeInvisible

    private void cmbCliente5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCliente5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCliente5ActionPerformed

    private void cmbCliente6PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbCliente6PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCliente6PopupMenuWillBecomeInvisible

    private void cmbCliente6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCliente6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCliente6ActionPerformed

    private void cmbCliente7PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbCliente7PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCliente7PopupMenuWillBecomeInvisible

    private void cmbCliente7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCliente7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCliente7ActionPerformed

    private void cmbCliente8PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_cmbCliente8PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCliente8PopupMenuWillBecomeInvisible

    private void cmbCliente8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCliente8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCliente8ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmbCliente;
    private javax.swing.JComboBox cmbCliente1;
    private javax.swing.JComboBox cmbCliente2;
    private javax.swing.JComboBox cmbCliente3;
    private javax.swing.JComboBox cmbCliente4;
    private javax.swing.JComboBox cmbCliente5;
    private javax.swing.JComboBox cmbCliente6;
    private javax.swing.JComboBox cmbCliente7;
    private javax.swing.JComboBox cmbCliente8;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private com.toedter.calendar.JDateChooser txtNasc1;
    private com.toedter.calendar.JDateChooser txtNasc2;
    private com.toedter.calendar.JDateChooser txtNasc3;
    private javax.swing.JTextField txtPesqNome;
    private javax.swing.JTextField txtPesqNome1;
    private javax.swing.JTextField txtPesqNome2;
    private javax.swing.JTextField txtPesqNome3;
    private javax.swing.JTextField txtPesqNome4;
    // End of variables declaration//GEN-END:variables

}
