/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * frmCadProduto.java
 *
 * Created on 22/05/2010, 13:56:09
 */

package frontEnd;

import java.beans.PropertyVetoException;

/**
 *
 * @author LAB1 PC15
 */
public class frmCadProduto extends javax.swing.JDialog {

    /** Creates new form frmCadProduto */
    public frmCadProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paineldesk = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().add(paineldesk, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        frameProduto frm = new frameProduto();
        paineldesk.add(frm);
        try{
            frm.setVisible(true);
            frm.setMaximum(true);
        }
        catch(PropertyVetoException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    /**
    * @param args the command line arguments
    */
   // public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmCadProduto dialog = new frmCadProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
    //    });
   // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane paineldesk;
    // End of variables declaration//GEN-END:variables

}
