package frontEnd;

import java.beans.PropertyVetoException;

public class frmCadFabricante extends javax.swing.JDialog {

    /** Creates new form frmCadCategoria */
    public frmCadFabricante(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desk = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de fabricante");
        setMinimumSize(new java.awt.Dimension(22, 262));
        setModal(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().add(desk, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       frameCadFabricante frm = new frameCadFabricante();
        desk.add(frm);
        try{
        frm.setVisible(true);
        frm.setMaximum(true);
        }catch(PropertyVetoException e){
        }
    }//GEN-LAST:event_formWindowOpened

            public void run() {
                frmCadFabricante dialog = new frmCadFabricante(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desk;
    // End of variables declaration//GEN-END:variables

}
